name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, build, Linux, X64]
    container:
      image: embeddedlinux/gcc:11-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls ${{ github.workspace }}
          pwd
          ls -al
