name: test
runs-on: [self-hosted, build, Linux]
on: [push, pull-request]

jobs:
  build:
    steps:
      - run: echo "Running test"
      - uses: actions/checkout@v3
        run: |
          ls ${{ github.workspace }}
          pwd
          ls -al
