name: test
on: [push]
env:
  HOME: /home/builder

jobs:
  build:
    runs-on: [self-hosted, build]
    strategy:
      matrix:
        include:
          - image: "embeddedlinux/gcc:11-22.04"
            preset: linux-gcc-debug
          - image: "embeddedlinux/clang:14-22.04"
            preset: linux-clang-debug
    name: ${{ matrix.preset }} (${{ matrix.image }})
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v3
      - name: Build 
        run: |
          mkdir ${{ github.run_id }}
          cd ${{ github.run_id }}

          cmake .. --preset ${{ matrix.preset }}
          make
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.preset }}
          path: ${{ github.run_id }}/bin

  test:
    runs-on: [self-hosted, build]
    name: test
    steps:
      - run: |
          pwd
          ls -al
