name: test
runs-on: self-hosted
on:
  push:
  pull_request:

jobs:
  build:
    steps:
      - run: echo "Running test"
      - uses: actions/checkout@v3
        run: |
          ls ${{ github.workspace }}
          pwd
          ls -al
